batch_size: 8
iters: 160000

train_dataset:
  type: Dataset
  dataset_root: /Users/aidc/work/generate_dataset/output/both/dataset
  train_path: /Users/aidc/work/generate_dataset/output/both/dataset/train.txt
  num_classes: 3
  mode: train
  transforms:
    - type: ResizeStepScaling
      min_scale_factor: 0.75
      max_scale_factor: 1.50
      scale_step_size: 0.25
    - type: RandomPaddingCrop
      crop_size: [768, 768]
      im_padding_value: 255
      label_padding_value: 255
      category_max_ratio: 0.95
    - type: RandomDistort
      brightness_range: 0.12
      contrast_range: 0.12
      saturation_range: 0.05
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

val_dataset:
  type: Dataset
  dataset_root: /Users/aidc/work/generate_dataset/output/both/dataset
  val_path: /Users/aidc/work/generate_dataset/output/both/dataset/val.txt
  num_classes: 3
  mode: val
  transforms:
    - type: Normalize
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]

optimizer:
  type: AdamW
  weight_decay: 0.01
  # custom_cfg:
  # - name: pos_embed
  #   weight_decay_mult: 0.0
  # - name: head
  #   lr_multi: 10.0
  # - name: bn
  #   weight_decay_mult: 0.0

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.0003
  end_lr: 1.0e-5
  power: 1.0
  warmup_iters: 5000
  warmup_start_lr: 1.0e-6

loss:
  types:
    - type: CrossEntropyLoss
      weight: [1.0, 4.0, 14.0]
      top_k_percent_pixels: 0.45
  coef: [1, 1, 1]


model:
  type: PPLiteSeg
  backbone:
    type: STDC2
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet2.tar.gz
